import { CriterionChip } from './Chip';
import { LISTING } from '@/lib/constants';
import { bpsToPercent, formatCompactUsd, formatInt, shortenAddress } from '@/lib/format';
import { SOLSCAN } from '@/lib/links';
import type { ListingsResult, TokenRow } from '@/lib/types';

const LISTING_TIERS = LISTING.tiers;

function VerdictChip({ token }: { token: TokenRow }) {
  if (token.listed) return <span className="chip chip--pass">listed</span>;
  if (token.incomplete) return <span className="chip chip--unverified">unverified</span>;
  return <span className="chip chip--fail">excluded</span>;
}

function Row({ token }: { token: TokenRow }) {
  const { market, sharingConfig } = token;

  return (
    <tr>
      <td>
        <div className="cell-symbol">
          <span className="cell-symbol__ticker">
            {market.symbol ?? 'UNKNOWN'}
          </span>
          <a
            className="cell-symbol__mint link"
            href={SOLSCAN.token(token.mint)}
            target="_blank"
            rel="noreferrer noopener"
          >
            {shortenAddress(token.mint, 6, 6)}
          </a>
        </div>
      </td>
      <td className="col-num">
        {formatCompactUsd(market.mcapUsd)}
        {market.mcapMismatch ? (
          <span
            className="muted"
            title={`DexScreener reports ${formatCompactUsd(
              market.reportedMcapUsd,
            )}, supply x price gives ${formatCompactUsd(
              market.computedMcapUsd,
            )}. The lower figure is used.`}
          >
            {' '}
            *
          </span>
        ) : null}
      </td>
      <td className="col-num">
        {token.holders === null ? (
          <span className="muted">unverified</span>
        ) : (
          formatInt(token.holders)
        )}
      </td>
      <td className="col-num">{bpsToPercent(token.ourShareBps)}</td>
      <td>
        <div className="chip-row">
          {token.criteria.map((c) => (
            <CriterionChip
              key={c.id}
              label={c.label}
              state={c.state}
              detail={c.detail}
            />
          ))}
        </div>
      </td>
      <td>
        <VerdictChip token={token} />
      </td>
      <td className="col-num">
        <a
          className="link"
          href={SOLSCAN.account(sharingConfig.address)}
          target="_blank"
          rel="noreferrer noopener"
          title={`Sharing config ${sharingConfig.address}`}
        >
          verify
        </a>
      </td>
    </tr>
  );
}

export default function ScreenerTable({
  listings,
  tokens,
  lane,
}: {
  listings: ListingsResult;
  /** The subset of rows this lane shows. Defaults to everything. */
  tokens?: TokenRow[];
  lane?: 'full' | 'partial';
}) {
  const rows = tokens ?? listings.tokens;

  if (rows.length === 0) {
    // An empty result only means "nobody has committed" when the scan actually
    // completed. If a slot scan failed we do not know what is out there, and
    // saying otherwise would be the one kind of claim this site cannot make.
    if (!listings.enumerationComplete) {
      return (
        <div className="table-wrap">
          <div className="empty">
            <div className="empty__title">Scan incomplete — cannot report</div>
            <p className="empty__body">
              At least one of the on-chain scans that finds participating coins
              did not return (the public RPC rate-limits this query hard). This
              table is therefore blank because we could not look, not because we
              looked and found nothing. It retries automatically.
            </p>
          </div>
        </div>
      );
    }

    if (lane === 'partial') {
      return (
        <div className="table-wrap">
          <div className="empty">
            <div className="empty__title">No projects in the lane yet</div>
            <p className="empty__body">
              This lane is for projects and memes routing{' '}
              {bpsToPercent(LISTING_TIERS.partialMinBps)} or more of their
              creator fees to the burn while keeping the rest. Generated by
              scanning the pump.fun fee program — it fills itself the moment
              someone commits.
            </p>
          </div>
        </div>
      );
    }

    if (lane === 'full') {
      // Scoped to this lane only: the project lane may hold committed configs,
      // so a blanket "nobody has committed" would be a false absence claim.
      return (
        <div className="table-wrap">
          <div className="empty">
            <div className="empty__title">
              Nobody has sent the full send yet
            </div>
            <p className="empty__body">
              No deployer has taken the {bpsToPercent(LISTING_TIERS.fullBps)}{' '}
              sole-recipient route yet — check the project lane for coins
              routing a partial share. The crown goes to the first ones in.
            </p>
          </div>
        </div>
      );
    }

    return (
      <div className="table-wrap">
        <div className="empty">
          <div className="empty__title">No fee-sharing configs found yet</div>
          <p className="empty__body">
            This table is generated by scanning the pump.fun fee program for
            sharing configs that name our wallet as a shareholder. It is empty
            because no deployer has committed yet — not because anything is
            hidden. It fills itself the moment one does.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="table-wrap">
      <table className="data">
        <caption className="sr-only">
          Coins routing pump.fun creator fees to the buyback, with the on-chain
          checks each one passes or fails.
        </caption>
        <thead>
          <tr>
            <th scope="col">Coin</th>
            <th scope="col" className="col-num">
              Market cap
            </th>
            <th scope="col" className="col-num">
              Holders
            </th>
            <th scope="col" className="col-num">
              Share to burns
            </th>
            <th scope="col">Criteria</th>
            <th scope="col">Verdict</th>
            <th scope="col" className="col-num">
              Proof
            </th>
          </tr>
        </thead>
        <tbody>
          {rows.map((token) => (
            <Row key={token.sharingConfig.address} token={token} />
          ))}
        </tbody>
      </table>
    </div>
  );
}
